### PR TITLE
Resolve quantiles issue

### PR DESCRIPTION
**Pull request by grantbabb**
Aims to close issue 13 and issue 4, two high priority bugs
- Removed choice of loading static quantiles data, 
- replaced with fast quantiles algo

### CODE REVIEW

**Comment by NathanSegerlind** [comment]
I ran this again (this time incorporating the fixes for issue 21, so we can get through the lda) and there are still some typos in the post processing:

<console>:23: error: not found: value sample
       val datagood = sample.filter(line => line.split(",").length == 27)
                      ^
add_time: (row: Array[String])Array[String]
<console>:25: error: not found: value datagood
       val data_with_time = datagood.map(_.trim.split(",")).map(add_time)
                            ^
<console>:42: error: not found: value data_with_time
                  time_cuts = distributed_quantiles(quant, compute_ecdf(data_with_time.map(row => row(27).toDouble )))
                                                                        ^
<console>:45: error: not found: value data_with_time
                  ibyt_cuts = distributed_quantiles(quant, compute_ecdf(data_with_time.map(row => row(17).toDouble )))
                                                                        ^
<console>:48: error: not found: value data_with_time
                  ipkt_cuts = distributed_quantiles(quint, compute_ecdf(data_with_time.map(row => row(16).toDouble )))
                                                                        ^
bin_ibyt_ipkt_time: (row: Array[String], ibyt_cuts: Array[Double], ipkt_cuts: Array[Double], time_cuts: Array[Double])Array[String]
<console>:31: error: not found: value data_with_time
       val binned_data = data_with_time.map(row => bin_ibyt_ipkt_time(row, ibyt_cuts, ipkt_cuts, time_cuts))
                         ^
adjust_port: (row: Array[String])Array[String]
<console>:25: error: not found: value binned_data
       val data_with_words = binned_data.map(row => adjust_port(row))
                             ^
<console>:41: error: not found: value data
       val src_scored = data.map(row => {
                        ^
<console>:25: error: not found: value src_scored
       var scored = src_scored.filter(elem => min(elem._1,elem._2) < threshold).sortByKey().map( row => row._3.mkString(",") )
                    ^
<console>:24: error: not found: value scored
              scored.persist(StorageLevel.MEMORY_AND_DISK)
              ^
<console>:26: error: not found: value scored
              scored.saveAsTextFile(scored_output_file)

**Comment by NathanSegerlind** [comment]
fm16 is back up and I've been testing there.... something is off with the data sets I tried on fm8... i kept on getting string parse errors (bad data)

**Comment by NathanSegerlind** [comment]
there is at least one more problem in the post processing:

src_scored: org.apache.spark.rdd.RDD[(Double, Double, Array[Any])] = MappedRDD[43] at map at <console>:69
<console>:73: error: value sortByKey is not a member of org.apache.spark.rdd.RDD[(Double, Double, Array[Any])]
       var scored = src_scored.filter(elem => min(elem._1,elem._2) < threshold).sortByKey().map( row => row._3.mkString(",") )
                                                                                ^
<console>:24: error: not found: value scored
              scored.persist(StorageLevel.MEMORY_AND_DISK)
              ^
<console>:26: error: not found: value scored
              scored.saveAsTextFile(scored_output_file)

**Comment by NathanSegerlind** [comment]
My typo fix is in https://github.com/Open-Network-Insight/oni-ml/pull/8

it doesn't handle the recently discovered sortByKey issue above, but some other typos

**Comment by grantbabb** [comment]
Take a breather ... you may be fixing "typos" that aren't typos.  If fm-16 is up, then I can take a look with "unfixed" code.

**Comment by grantbabb** [comment]
ML pipeline completed as expected.  Quantiles were calculated the same in both pre and post steps, using the same dataset

Manually merged changes from #8 - add'l pull request not needed.

**Comment by natedogs911** [comment]
this resolves Open-Network-Insight/open-network-insight#13

**Pull request merged**
