### PR TITLE
Hot fix - ml_ops.sh not using passed parameter tolerance, always using /etc/duxbay.conf

### PR DESCRIPTION
**Pull request by rabarona**
Aims to close https://github.com/Open-Network-Insight/open-network-insight/issues/72

Changed ml_ops to validate if variable $3 is empty and if not, assign the value to variable TOL.
`if [ $3 != '' ]; then TOL=$3 ; fi export TOL`

### CODE REVIEW

**Comment by EverLoSa** [comment]
I would change the validation to : 
if [ -n "$3" ]; then TOL=$3 ; fi export TOL

**Comment by rabarona** [comment]
@EverLoSa I made a change to implement your suggestion.

**Comment by NathanSegerlind** [comment]
this one has been tested I take it, as part of your dns feedback tests?

**Comment by rabarona** [comment]
@NathanSegerlind Yes, I actually merged this branch into intelml_feedback to test.

**Pull request merged**
