### PR TITLE
mpi_cmd

### PR DESCRIPTION
**Pull request by NathanSegerlind**
MPI execution now controlled by MPI_PREP_CMD and MPI_CMD.

MPI_PREP_CMD: command necessary to prepare for running MPI (loading of environment variables or somesuch)
MPI_CMD : command to execute MPI

### CODE REVIEW

**Comment by NathanSegerlind** [comment]
tested on or8, which uses

MPI_PREP_CMD='export LD_LIBRARY_PATH=/usr/local/lib'
MPI_CMD='mpiexec'

and tested on lasvdb, which uses:

MPI_CMD='mpiexec.hydra'
MPI_PREP_CMD=''

**Comment by NathanSegerlind** [comment]
sister PR for oni-setup: https://github.com/Open-Network-Insight/oni-setup/pull/9

**Comment by natedogs911** [comment]
LGTM

**Comment by NathanSegerlind** [comment]
merging into a different branch

**Pull request closed without merging**
