### PR TITLE
issue39_path_separation

### PR DESCRIPTION
**Pull request by NathanSegerlind**
```
DPATH is now two separate variables:
FLOWPATH - the location of the ingested netflow data
DNSPATH - the location of the ingested DNS data
```

Needed to merge DNS analysis into 1.0.1

### CODE REVIEW

**Comment by grantbabb** [comment]
This is not scalable.  The $DSOURCE variable is passed in via ml_ops.sh or run_oa.sh, and it builds based on the data source.

I believe people are not observing that $DSOURCES and $DSOURCE are two separate variables that perform different functions, and are documented as such

**Comment by NathanSegerlind** [comment]
"not scalable" - in what way? as more input sources are added?

But the important thing is to solve Ricardo's problem,  where the flow and DNS are kept in two completely different stores... https://github.com/Open-Network-Insight/open-network-insight/issues/39

anyway, the current documentation at https://github.com/Open-Network-Insight/open-network-insight/wiki/Edit%20Solution%20Configuration identifies DPATH as the path to the flow records, not a common store containing both flow and DNS data

anyway, important thing is to get system working now and DNS and flow are not in a common store

**Comment by grantbabb** [comment]
I thought this was a separate issue.  I thought this had already been merged when we discussed some time ago.

OK to merge.

**Comment by grantbabb** [comment]
The better approach would be to leave one variable as DPATH, then add the temporary path as DNSPATH.  That way it can be removed in 1.0.1 with minimal disruption.

**Comment by NathanSegerlind** [comment]
1. Ricardo has tested the code and it works. 
2. Regarding DPATH versus FLOW_PATH:  FLOW_PATH is a far more meaningful name.

**Pull request merged**
