### PR TITLE
ML  restructuring

### PR DESCRIPTION
**Pull request by NathanSegerlind**
This includes several changes.

ml pipeline is now built as a jar using sbt for dependency management and build
ml_ops now sends this jar to spark submit
duplicated code now moved into libraries
first pass refactoring / code style changes
unit test framework added as well as unit tests for some of the code (quantiles and ecdf)
bug fix for quantiles

TESTING

flow without feedback
flow with feedback
DNS with feedback
DNS without feedback
all four paths run and eye-ball inspection of results "makes sense"

### CODE REVIEW

**Comment by natedogs911** [comment]
LGTM, i'd like to setup some time for a briefing on all the changes

**Comment by rabarona** [comment]
LGTM

**Comment by NathanSegerlind** [comment]
thanks to Ricardo for all his hard work!

**Comment by EverLoSa** [comment]
LGTM

**Pull request merged**
